version: 2

jobs:
  install_deps:
    docker:
      - image: circleci/node:10.14.0
    working_directory: ~/workspace

    steps:
      - checkout

workflows:
  version: 2

  build:
    jobs:
      - install_deps